#pragma once

namespace PFM {

	enum class simFuncEnum { DATA_CONTROL_TEST, SINGLE_LAYER_CH_SIM, MULTI_LAYER_CH_SIM, TOTAL_SIM_FUNCS};
	//TODO: Add BEST_CIRCULAR_PACKING, BEST_HEXAGONAL_PACKING and FORCED_CONCENTRATION_RANDOM
	enum class initialConditions { EVENLY_SPACED_INDEX, LINEAR_RANDOM, TOTAL_INITIAL_CONDS};
	enum class integrationMethods { FTCS, FTCS_WITH_SUBS, HEUN, RK2, RK4, TOTAL_METHODS };

}