# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86_64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86_64)
  simulation_config = debug_x86_64
  controlCL_config = debug_x86_64
  controlGUI_config = debug_x86_64
endif
ifeq ($(config),release_x86_64)
  simulation_config = release_x86_64
  controlCL_config = release_x86_64
  controlGUI_config = release_x86_64
endif

PROJECTS := simulation controlCL controlGUI

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

simulation:
ifneq (,$(simulation_config))
	@echo "==== Building simulation ($(simulation_config)) ===="
	@${MAKE} --no-print-directory -C simulation -f Makefile config=$(simulation_config)
endif

controlCL: simulation
ifneq (,$(controlCL_config))
	@echo "==== Building controlCL ($(controlCL_config)) ===="
	@${MAKE} --no-print-directory -C controlCL -f Makefile config=$(controlCL_config)
endif

controlGUI: simulation
ifneq (,$(controlGUI_config))
	@echo "==== Building controlGUI ($(controlGUI_config)) ===="
	@${MAKE} --no-print-directory -C controlGUI -f Makefile config=$(controlGUI_config)
endif

clean:
	@${MAKE} --no-print-directory -C simulation -f Makefile clean
	@${MAKE} --no-print-directory -C controlCL -f Makefile clean
	@${MAKE} --no-print-directory -C controlGUI -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86_64"
	@echo "  release_x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   simulation"
	@echo "   controlCL"
	@echo "   controlGUI"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"